trigger: none

# Don't run against PRs
pr: none

stages:
- script: |
    sudo apt-get update
    sudo apt-get install jq
  displayName: 'Install jq JSON processor'
- script: |
    version_val=$(jq -r '.version' package.json)
    echo "$version_val" 
  displayName: 'Extract version value'  











